version: '3'

services:
  currency-converter-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: currency-converter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    networks:
      - currency-converter-network

  currency-converter-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/currency-converter
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.flyway.schemas=currency-converter
      - spring.jpa.properties.hibernate.default_schema=currency-converter
    ports:
      - "8080:8080"
    depends_on:
      - currency-converter-postgres
    networks:
      - currency-converter-network

networks:
  currency-converter-network:
    driver: bridge
